# Generated by Django 4.2 on 2023-04-24 09:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0c27954f-e147-4c36-aa17-df5900690650'), editable=False),
        ),
    ]
