# Generated by Django 4.2 on 2023-04-24 10:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_crud', '0002_classroom_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5da774cf-e69c-439d-946f-e0d9e45a3355'), editable=False),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.UUID('5da774cf-e69c-439d-946f-e0d9e45a3355'), editable=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_people', to='api_crud.classroom')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
