# Generated by Django 4.2 on 2023-04-25 10:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_crud', '0003_alter_classroom_uuid_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c294ebf7-fde9-44e5-82b0-27947d0a19a9'), editable=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c294ebf7-fde9-44e5-82b0-27947d0a19a9'), editable=False),
        ),
    ]
