# Generated by Django 4.2 on 2023-04-25 10:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_crud', '0004_alter_classroom_uuid_alter_person_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6c76d235-ba3c-40f6-9843-40553fd3f04b'), editable=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6c76d235-ba3c-40f6-9843-40553fd3f04b'), editable=False),
        ),
        migrations.CreateModel(
            name='PersonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.UUID('6c76d235-ba3c-40f6-9843-40553fd3f04b'), editable=False)),
                ('profile_picture', models.FileField(blank=True, null=True, upload_to='api_crud')),
                ('address', models.CharField(max_length=50)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person_profile', to='api_crud.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
